import { useState } from 'react';
import { registerServer } from '../api/client.js';
import { Link } from 'react-router-dom';

export default function Register() {
  const [form, setForm] = useState({
    serverID: '',
    publicKey: '',
    institution: '',
    description: '',
  });
  const [submitting, setSubmitting] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);

  const onChange = (key) => (e) => setForm({ ...form, [key]: e.target.value });

  const onSubmit = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);
    setResult(null);
    try {
      const payload = {
        serverID: form.serverID.trim(),
        publicKey: form.publicKey.trim(),
        institution: form.institution.trim(),
        description: form.description.trim(),
      };
      const res = await registerServer(payload);
      setResult({ ...res, serverID: payload.serverID });
      // Persist locally so it appears in the overview even if the gateway
      // has no GET /api/servers endpoint.
      try {
        const list = JSON.parse(localStorage.getItem('bdrvs.knownServers') || '[]');
        if (!list.includes(payload.serverID)) {
          list.push(payload.serverID);
          localStorage.setItem('bdrvs.knownServers', JSON.stringify(list));
        }
      } catch {
        /* ignore */
      }
      setForm({ serverID: '', publicKey: '', institution: '', description: '' });
    } catch (err) {
      setError(err.message || String(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <div className="page-head">
        <div>
          <span className="eyebrow">Tier 2 · On-chain identity</span>
          <h1 style={{ marginTop: '0.5rem' }}>Register health server</h1>
        </div>
      </div>

      <section className="panel" style={{ maxWidth: 720 }}>
        <div className="panel__head">
          <span className="panel__title">Server registration</span>
          <span className="eyebrow">POST /api/register</span>
        </div>
        <div className="panel__body">
          {result && (
            <div className="success-box">
              Server <strong>{result.serverID}</strong> registered. Its public key is now
              recognised by the residency chaincode and check-ins may begin.{' '}
              <Link to={`/servers/${encodeURIComponent(result.serverID)}`}>Open record →</Link>
            </div>
          )}
          {error && <div className="error-box">{error}</div>}

          <form onSubmit={onSubmit}>
            <div className="form-row">
              <label htmlFor="serverID">Server identifier</label>
              <input
                id="serverID"
                value={form.serverID}
                onChange={onChange('serverID')}
                placeholder="LHIMS-KORLE-BU-02"
                required
              />
            </div>

            <div className="form-row">
              <label htmlFor="institution">Institution</label>
              <input
                id="institution"
                value={form.institution}
                onChange={onChange('institution')}
                placeholder="Korle-Bu Teaching Hospital"
              />
            </div>

            <div className="form-row">
              <label htmlFor="description">Description (optional)</label>
              <input
                id="description"
                value={form.description}
                onChange={onChange('description')}
                placeholder="LHIMS production node — patient records"
              />
            </div>

            <div className="form-row">
              <label htmlFor="publicKey">ECDSA P-256 public key (PEM)</label>
              <textarea
                id="publicKey"
                value={form.publicKey}
                onChange={onChange('publicKey')}
                placeholder={
                  '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE…\n-----END PUBLIC KEY-----'
                }
                required
              />
            </div>

            <div className="row-actions" style={{ justifyContent: 'flex-end' }}>
              <button type="submit" className="btn" disabled={submitting}>
                {submitting ? 'Submitting…' : 'Register server'}
              </button>
            </div>
          </form>
        </div>
      </section>

      <p
        style={{
          marginTop: '1.5rem',
          fontFamily: 'var(--font-mono)',
          fontSize: '0.75rem',
          color: 'var(--ink-3)',
          lineHeight: 1.6,
          maxWidth: 720,
        }}
      >
        The public key is the one generated by the probing agent's <span className="mono">key_manager.py</span>{' '}
        on the vendor's health server. Once registered, the smart contract uses it to verify the
        ECDSA signature on every check-in payload.
      </p>
    </>
  );
}
