import { useState } from 'react'
import { api } from '../utils/api'
import './Register.css'

export default function Register() {
  const [form, setForm] = useState({ serverID:'', publicKey:'', operator:'', facility:'', city:'', lat:'', lng:'' })
  const [state, setState] = useState('idle')
  const [msg, setMsg] = useState('')
  const set=(k,v)=>setForm(f=>({...f,[k]:v}))

  async function handleSubmit(){
    const req=['serverID','publicKey','operator','facility']
    for(const k of req){ if(!form[k].trim()){ setMsg(`"${k}" is required.`); setState('error'); return } }
    setState('loading')
    try{
      const res=await api.register({ serverID:form.serverID.trim(), publicKey:form.publicKey.trim(), operator:form.operator.trim(), facility:form.facility.trim(), city:form.city.trim(), latitude:form.lat?parseFloat(form.lat):undefined, longitude:form.lng?parseFloat(form.lng):undefined })
      setMsg(res.data?.message||'Server registered successfully.')
      setState('success')
      setForm({ serverID:'', publicKey:'', operator:'', facility:'', city:'', lat:'', lng:'' })
    }catch(e){ setMsg(e.response?.data?.error||e.message||'Registration failed.'); setState('error') }
  }

  return(
    <div className="register-page fade-in">
      <div className="page-banner info-banner">
        <div className="banner-icon">+</div>
        <div>
          <div className="banner-title">Register Health Server</div>
          <div className="banner-sub">Enrol a new vendor-hosted health server on the B-DRVS ledger for continuous residency monitoring.</div>
        </div>
      </div>
      <div className="reg-grid">
        <div className="card reg-card">
          <div className="card-header"><span className="card-title">Server Identity</span></div>
          <div className="form-body">
            <Field label="Server ID *" hint="e.g. LHIMS-RIDGE-01"><input className="field-input mono" placeholder="LHIMS-FACILITY-XX" value={form.serverID} onChange={e=>set('serverID',e.target.value)}/></Field>
            <Field label="Operator / Vendor *" hint="Name of the deploying vendor"><input className="field-input" placeholder="e.g. Lightwave Technologies Ltd." value={form.operator} onChange={e=>set('operator',e.target.value)}/></Field>
            <Field label="Facility Name *" hint="Full name of the health facility"><input className="field-input" placeholder="e.g. Ridge Hospital, Accra" value={form.facility} onChange={e=>set('facility',e.target.value)}/></Field>
            <div className="field-row">
              <Field label="City / Region" hint="Optional"><input className="field-input" placeholder="e.g. Accra" value={form.city} onChange={e=>set('city',e.target.value)}/></Field>
              <Field label="Latitude" hint="For map"><input className="field-input mono" placeholder="5.6037" type="number" value={form.lat} onChange={e=>set('lat',e.target.value)}/></Field>
              <Field label="Longitude" hint="For map"><input className="field-input mono" placeholder="-0.1870" type="number" value={form.lng} onChange={e=>set('lng',e.target.value)}/></Field>
            </div>
          </div>
        </div>
        <div className="card reg-card">
          <div className="card-header"><span className="card-title">ECDSA Public Key</span></div>
          <div className="form-body">
            <Field label="Agent Public Key (PEM) *" hint="Paste the ECDSA P-256 public key generated by the probing agent">
              <textarea className="field-textarea mono" rows={8} placeholder={"-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQY...\n-----END PUBLIC KEY-----"} value={form.publicKey} onChange={e=>set('publicKey',e.target.value)}/>
            </Field>
            <div className="key-note">
              <span className="note-icon">ℹ</span>
              The public key is stored on the blockchain and used by the smart contract to verify all signed check-in payloads from this server.
            </div>
          </div>
        </div>
      </div>
      {msg&&<div className={`status-msg ${state==='success'?'msg-success':'msg-error'}`}><span>{state==='success'?'✓':'✕'}</span><span>{msg}</span></div>}
      <div className="form-actions">
        <button className={`submit-btn${state==='loading'?' loading':''}`} onClick={handleSubmit} disabled={state==='loading'}>
          {state==='loading'?'Submitting to Ledger…':'Register on Blockchain'}
        </button>
        <div className="submit-note">Registration requires endorsement from both MoH and NITA peer nodes.</div>
      </div>
    </div>
  )
}
function Field({label,hint,children}){
  return(<div className="field-group"><label className="field-label">{label}</label>{hint&&<div className="field-hint">{hint}</div>}{children}</div>)
}
